In [2]:
# imports
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam
from simanneal import Annealer
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [13]:
df = pd.read_csv('Cars.csv', sep=';')

df.head(5)

,Manufacturer,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,Cylinders,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Model
0,Acura,Small,12.9,15.9,18.8,25,31,No airbag,Front,4,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,Acura,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,6,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,Audi,Compact,25.9,29.1,32.3,20,26,Driver only,Front,6,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,Audi,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,6,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,BMW,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,4,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [14]:
# b
df['Model'] = df['Model'].str.split(' ').str.get(1)

df.head(5)

,Manufacturer,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,Cylinders,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Model
0,Acura,Small,12.9,15.9,18.8,25,31,No airbag,Front,4,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Integra
1,Acura,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,6,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Legend
2,Audi,Compact,25.9,29.1,32.3,20,26,Driver only,Front,6,...,5,180,102,67,37,28.0,14.0,3375,non-USA,90
3,Audi,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,6,...,6,193,106,70,37,31.0,17.0,3405,non-USA,100
4,BMW,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,4,...,4,186,109,69,39,27.0,13.0,3640,non-USA,535i

In [16]:
names = pd.DataFrame({
    "Name": ["Alice Smith", "Bob Johnson", "Charlie Brown", "Diana White", "Eva Green"]
})

names.head(5)

            Name
0    Alice Smith
1    Bob Johnson
2  Charlie Brown
3    Diana White
4      Eva Green

In [ ]:
names['Lastname'] = names['Name'].str.split(' ').str.get(1)

names.head(5)

            Name Lastname
0    Alice Smith    Smith
1    Bob Johnson  Johnson
2  Charlie Brown    Brown
3    Diana White    White
4      Eva Green    Green

In [21]:
#stel ik wil die lastname dan uit name verwijderen doe ik:
names["Name"] = names["Name"].str.split(" ").str[:-1].str.join(" ")
names.head(5)

      Name Lastname
0    Alice    Smith
1      Bob  Johnson
2  Charlie    Brown
3    Diana    White
4      Eva    Green

In [23]:
df = pd.DataFrame({
    "Name": ["Alice Smith", "Bob Johnson", "Charlie Brown", "Diana White", "Eva Green"]
})

# 1. Simpele vervanging
df["Name"] = df["Name"].str.replace("Smith", "⭐", regex=False)

# 2. Alles lowercase maken en 'a' → '@'
df["Name"] = df["Name"].str.lower().str.replace("a", "@", regex=False)

# 3. Regex gebruiken: vervang alle spaties door '_'
df["Name"] = df["Name"].str.replace(r"\s+", "_", regex=True)

print(df)

            Name
0        @lice_⭐
1    bob_johnson
2  ch@rlie_brown
3    di@n@_white
4      ev@_green

In [24]:
# Letters
# [A-Za-z]    → alle letters
# [A-Z]       → hoofdletters
# [a-z]       → kleine letters

# Cijfers
# [0-9]       → cijfers
# \d          → cijfers (digit)
# \D          → niet-cijfers

# Whitespace (spaties e.d.)
# \s          → whitespace (spatie, tab, newline)
# \S          → alles behalve whitespace
# " "         → gewone spatie

# Specifieke tekens
# \.          → punt
# \,          → komma
# \-          → minteken/streep
# _           → underscore
# @           → at-tekentje
# #           → hashtag
# \$          → dollar (moet escaped worden)
# %           → procent
# &           → ampersand
# \+          → plus
# \*          → sterretje
# \/          → slash
# \\          → backslash

# Symbolische klassen
# \w          → "word characters" (letters, cijfers, underscore)
# \W          → niet-woordtekens (bv. spaties, symbolen)
# \b          → woordgrens
# .           → gelijk welk teken (behalve newline)

# Andere handige regex dingen
# ^           → begin van string
# $           → einde van string
# ?           → optioneel
# +           → 1 of meer keer
# *           → 0 of meer keer